name: Update Dependencies
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to update dependencies on'
        required: true
        type: string

permissions:
  contents: write
jobs:
  run:
    runs-on: ubuntu-latest
    name: Update licensed cache
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - run: npm ci

      - name: Install licensed
        run: |
          cd $RUNNER_TEMP
          curl -Lfs -o licensed.tar.gz https://github.com/github/licensed/releases/download/3.6.0/licensed-3.6.0-linux-x64.tar.gz
          sudo tar -xzf licensed.tar.gz
          sudo mv licensed /usr/local/bin/licensed
      - run: licensed cache

      - name: Rebuild the dist/ directory
        run: |
          npm run build:compile
          npm run build:package

      - name: Commit changes as Dependabot
        run: |
          git config --global user.name 'dependabot[bot]'
          git config --global user.email '49699333+dependabot[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update licensed cache and dist/ directory"
          git push
